[package]
name = "stm32f446-rs-template"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
nb = "1.1.0"
panic-halt = "0.2.0"
rtt-target = "0.5.0"


[dependencies.stm32f4xx-hal]
version = "0.21.0"
features = ["stm32f446"]
